server {
    listen 80;
    listen [::]:80;

    server_name upskillrh.com.br www.upskillrh.com.br upskillrh.online www.upskillrh.online;
    root /var/www/upskillrh.com.br;
    index index.html;

    access_log /var/log/nginx/upskillrh.com.br.access.log;
    error_log /var/log/nginx/upskillrh.com.br.error.log;

    location = /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
